
CREATE TABLE role (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    name VARCHAR (255) NOT NULL
);

CREATE TABLE player (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    description VARCHAR (255) NULL,
    email VARCHAR (255) UNIQUE NOT NULL,
    first_name VARCHAR (255) NOT NULL,
    last_name VARCHAR (255) NOT NULL,
    password VARCHAR (255) NOT NULL,
    phone_number VARCHAR (20) NULL
);

CREATE TABLE football_match (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    owner_id BIGINT NOT NULL,
    start_date TIMESTAMP NOT NULL,
    location VARCHAR (255) NOT NULL,
    title VARCHAR (255) NOT NULL,
    description VARCHAR (255) NOT NULL,
    number_of_player INTEGER NOT NULL,
    match_status INTEGER NOT NULL
);

CREATE TABLE users_roles (
    user_id BIGINT,
    role_id BIGINT
);

CREATE TABLE password_reset_token (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    token VARCHAR(255) UNIQUE NOT NULL,
    user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL
);
